messages:
  selectBlock: §6[§4Marteau§6] §2Bloc sélectionné
  replaceBlock: §6[§4Marteau§6] §2Bloc déplacée
  mustSelectFirst: §6[§4Marteau§6] §cVeuillez d'abord sélectionner un bloc avec un
    clic gauche
  canOnlyReplaceDirt: §6[§4Marteau§6] §cVous ne pouvez que déplacée sur bloc de terre
  mustPlaceSelected: §6[§4Marteau§6] §cVous devez d'abord poser le bloc sélectionné
    avant d'en sélectionner un nouveau.
  cannotSelectBlock: §6[§4Marteau§6] §cVous ne pouvez pas sélectionner ce type bloc.
  trollMessage: §6[§4Marteau§6] §cC'est pas très malin de remplacer de la §6terre§c
    par de la §6terre§a ;)
  RegionMessage: §6[§4Marteau§6] §cCette region est protégée
selectionItem:
  material: BONE
  displayName: '&6Marteau'
  lore:
  - '&cPermet de déplacer un bloc tout en conservant son état'
nonSelectableBlocks:
- BEDROCK
- CHEST
- TRAPPED_CHEST
- SHULKER_BOX
- AIR
- TRIAL_SPAWNER
- VAULT
- WHITE_SHULKER_BOX
- ORANGE_SHULKER_BOX
- MAGENTA_SHULKER_BOX
- LIGHT_BLUE_SHULKER_BOX
- YELLOW_SHULKER_BOX
- LIME_SHULKER_BOX
- PINK_SHULKER_BOX
- GRAY_SHULKER_BOX
- LIGHT_GRAY_SHULKER_BOX
- CYAN_SHULKER_BOX
- PURPLE_SHULKER_BOX
- BLUE_SHULKER_BOX
- BROWN_SHULKER_BOX
- GREEN_SHULKER_BOX
- RED_SHULKER_BOX
- BLACK_SHULKER_BOX
- BARREL
- REINFORCED_DEEPSLATE
- BARRIER
- FURNACE
- BLAST_FURNACE
- SPAWNER
- MOB_SPAWNER
- WALL_SIGN
- SIGN_POST
- PORTAL
- END_PORTAL_FRAME
- END_PORTAL
- END_GATEWAY
